# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.oschina.net/wtMal/malpodspecs.git'

target 'MALAnimationExample' do

pod 'pop', '~> 1.0.7'
pod 'GPUImage', '~> 0.1.6'
pod 'iCarousel', '~> 1.8.1'
pod 'SOZOChromoplast', '~> 0.0.2'
pod 'MNetMonitor', '~> 1.0.1'

end


